// /decks/decks.ts
export type PreconName =
  | "Avatar of Air"
  | "Avatar of Earth"
  | "Avatar of Fire"
  | "Avatar of Water"
  | "Flamecaller"
  | "Sparkmage"
  | "Waveshaper"
  | "Geomancer"
  | "Savior"
  | "Necromancer"
  | "Persecutor"
  | "Harbinger";

export type PreconList = string[];
export type PreconCollection = Record<PreconName, PreconList>;

/** All precons live here, keyed by deck name. */
export const PRECONS: Record<PreconName, PreconList> = {
  "Avatar of Air": [
    "Lightning Bolt x3",
    "Chain Lightning x2",
    "Thunderstorm",
    "Apprentice Wizard x2",
    "Grandmaster Wizard",
    "Blink x2",
    "Waypoint Portal",
    "Cloud Spirit x2",
    "Spectral Stalker x2",
    "Headless Haunt x2",
    "Snow Leopard x2",
    "Plumed Pegasus x2",
    "Gyre Hippogriffs",
    "Spire Lich",
    "Kite Archer",
    "Roaming Monster",
    "Midnight Rogue",
    "Peregrine Apparition",
    "Sling Pixies",
    "Skirmishers of Mu",
    "Nimbus Jinn",
    "Nightmare",
    "Devil's Egg",
    "Doomsday Device",
    "Lone Tower x3",
    "Dark Tower x3",
    "Gothic Tower x3",
    "Updraft Ridge x2",
    "Mountain Pass x2",
    "Observatory",
    "Cloud City",
    "Bottomless Pit",
  ],
  "Avatar of Earth": [
    "King of the Realm",
    "Queen of Midland",
    "Midland Army",
    "Land Surveyor x2",
    "House Arn Bannerman x2",
    "Scent Hound",
    "Belmotte Longbowmen x3",
    "Frontier Settlers",
    "Wild Boars x2",
    "Amazon Warriors x2",
    "Autumn Unicorn x2",
    "Cave Trolls x3",
    "Pudge Butcher x2",
    "Mountain Giant",
    "Stone Gaze Gorgons",
    "Wraetannis Titan",
    "Overpower x2",
    "Bury x2",
    "Earthquake",
    "Entangle Terrain",
    "Craterize",
    "Siege Ballista",
    "Screaming Skull",
    "Spear of Destiny",
    "Rustic Village",
    "Humble Village",
    "Simple Village",
    "Holy Ground x2",
    "Vantage Hills x3",
    "Quagmire x2",
  ],
"Avatar of Fire": [
    "Ancient Dragon",
    "Colicky Dragonettes",
    "Incinerate",
    "Firebolts",
    "Heat Ray",
    "Fireball x2",
    "Minor Explosion x2",
    "Major Explosion",
    "Wildfire",
    "Blaze",
    "Quarrelsome Kobolds",
    "Sacred Scarabs x2",
    "Raal Dromedary x2",
    "Pit Vipers x2",
    "Ogre Goons x2",
    "Clamor of Harpies x2",
    "Hillock Basilisk",
    "Bull Demons of Adum",
    "Petrosian Cavalry",
    "Rimlands Nomad x2",
    "Wayfaring Pilgrim x2",
    "Doomsday Prophet",
    "Sand Worm x2",
    "Will's-o'-the-Wisp",
    "Infernal Legion",
    "Drums of Doom",
    "Red Desert",
    "Remote Desert",
    "Arid Desert",
    "Shifting Sands",
    "Standing Stones",
    "River of Flame",
    "Cornerstone",
    "Versuvius",
  ],

  "Avatar of Water": [
    "Diluvian Kraken",
    "Unland Angler",
    "Guile Sirens",
    "Tide Naiads x2",
    "Deep-sea Mermaids x2",
    "Anui Undine",
    "Mother Nature",
    "Swan Maidens",
    "Swamp Buffalo x2",
    "Coral-reef Kelpie x2",
    "Polar Bears x2",
    "Sedge Crabs",
    "Megamoeba",
    "Brobdingnag Bullfrog x2",
    "Sea Serpent x2",
    "Pirate Ship",
    "Marine Voyage",
    "Dodge Roll x2",
    "Drown x2",
    "Frost Nova",
    "Ice Lance x2",
    "Rip Tide",
    "Upwelling",
    "Flood",
    "Wrath of the Sea",
    "Sunken Treasure",
    "Spring River x3",
    "Summer River x3",
    "Autumn River x3",
    "Undertow x2",
    "Flood Plain x2",
    "Island Leviathan",
    "Maelstrom",
    "Tadpole Pool",
  ],
    "Flamecaller": [
    "Pit Vipers x2",
    "Raal Dromedary x2",
    "Lava Salamander x1",
    "Rimland Nomads x2",
    "Sacred Scarabs x2",
    "Wayfaring Pilgrim x2",
    "Colicky Dragonettes x1",
    "Ogre Goons x3",
    "Quarrelsome Kobolds x1",
    "Clamor of Harpies x1",
    "Hillock Basilisk x1",
    "Petrosian Cavalry x1",
    "Sand Worm x2",
    "Askelon Phoenix x1",
    "Escyllion Cyclops x1",
    "Infernal Legion x1",
    "Firebolts x2",
    "Mad Dash x1",
    "Blaze x1",
    "Heat Ray x1",
    "Minor Explosion x2",
    "Fireball x1",
    "Incinerate x1",
    "Cone of Flame x1",
    "Major Explosion x1",
    "Arid Desert x4",
    "Cornerstone x1",
    "Red Desert x4",
    "Remote Desert x4",
    "Shifting Sands x2",
    "Vesuvius x1",
  ],
    "Sparkmage": [
    "Thunderstorm x1",
    "Lucky Charm x1",
    "Lone Tower x3",
    "Lightning Bolt x3",
    "Gothic Tower x3",
    "Dark Tower x3",
    "Updraft Ridge x2",
    "Spectral Stalker x2",
    "Snow Leopard x2",
    "Plumed Pegasus x2",
    "Mountain Pass x2",
    "Midnight Rogue x2",
    "Headless Haunt x2",
    "Dead of Night Demon x2",
    "Cloud Spirit x2",
    "Chain Lightning x2",
    "Blink x2",
    "Apprentice Wizard x2",
    "Teleport x1",
    "Spire Lich x1",
    "Sling Pixies x1",
    "Skirmishers of Mu x1",
    "Roaming Monster x1",
    "Raise Dead x1",
    "Planar Gate x1",
    "Observatory x1",
    "Nimbus Jinn x1",
    "Kite Archer x1",
    "Highland Clansmen x1",
    "Gyre Hippogriffs x1",
    "Grandmaster Wizard x1",
    "Cloud City x1",
  ],
  "Waveshaper": [
    "Undertow x3",
    "Summer River x3",
    "Spring River x3",
    "Autumn River x3",
    "Tide Naiads x2",
    "Swamp Buffalo x2",
    "Sea Serpent x2",
    "Riptide x2",
    "Polar Bears x2",
    "Pirate Ship x2",
    "Ice Lance x2",
    "Floodplain x2",
    "Drown x2",
    "Deep-Sea Mermaids x2",
    "Coral-Reef Kelpie x2",
    "Anui Undine x2",
    "Wrath of the Sea x1",
    "Tufted Turtles x1",
    "Swan Maidens x1",
    "Sunken Treasure x1",
    "Stormy Seas x1",
    "Seirawan Hydra x1",
    "Sedge Crabs x1",
    "Porcupine Pufferfish x1",
    "Mariner's Curse x1",
    "Maelström x1",
    "Island Leviathan x1",
    "Guile Sirens x1",
    "Font of Life x1",
    "Flood x1",
    "Diluvian Kraken x1",
    "Brobdingnag Bullfrog x1",
  ],
    "Geomancer": [
    "Simple Village x3",
    "Rustic Village x3",
    "Humble Village x3",
    "Cave Trolls x3",
    "Belmotte Longbowmen x3",
    "Wild Boars x2",
    "Vantage Hills x2",
    "Scent Hounds x2",
    "Quagmire x2",
    "Overpower x2",
    "Land Surveyor x2",
    "House Arn Bannerman x2",
    "Bury x2",
    "Autumn Unicorn x2",
    "Amazon Warriors x2",
    "Wraetannis Titan x1",
    "Slumbering Giantess x1",
    "Sinkhole x1",
    "Siege Ballista x1",
    "Rolling Boulder x1",
    "Pudge Butcher x1",
    "Payload Trebuchet x1",
    "Mountain Giant x1",
    "King of the Realm x1",
    "Holy Ground x1",
    "Entangle Terrain x1",
    "Divine Healing x1",
    "Dalcean Phalanx x1",
    "Craterize x1",
    "Cave-In x1",
    "Border Militia x1",
    "Bedrock x1",
  ],
  "Savior": [
    "Flame of the First Ones x1",
    "Makeshift Barricade x1",
    "Eltham Townsfolk x1",
    "Revered Revenant x2",
    "Serava Townsfolk x1",
    "Town Priest x1",
    "Angel Ascendant x1",
    "Muddy Pigs x2",
    "Survivors of Serava x2",
    "Virgin in Prayer x2",
    "Mayor of Milborne x1",
    "Nightwatchmen x1",
    "Order of the White Wing x1",
    "Rowdy Boys x1",
    "Search Party x3",
    "Guardian Angel x1",
    "Monks of Kobalsa x2",
    "Weathered Trunks x2",
    "Faith Incarnate x1",
    "Malakhim x1",
    "Enduring Faith x1",
    "Wave of Eviction x1",
    "Baptize x1",
    "Divine Lance x1",
    "Holy Nova x1",
    "Smite x2",
    "Golden Dawn x1",
    "Algae Bloom x1",
    "Autumn Bloom x2",
    "Blessed Village x2",
    "Blessed Well x1",
    "Consecrated Ground x1",
    "Fertile Earth x1",
    "Forlorn Keep x1",
    "Mudslide x1",
    "Stream x2",
    "Troubled Town x2",
    "Valley x2",
  ],
  "Persecutor": [
    "Holy Water x1",
    "Blade of Thorns x1",
    "Peacemaker Arbalest x1",
    "One-shot Wizard x1",
    "Flagellant x1",
    "Flaming Skull x1",
    "Holy Warrior x2",
    "Kissers of Wounds x1",
    "Lesser Blood Demon x2",
    "Redmane Hyena x1",
    "Wild Fanatic x2",
    "Intrepid Hero x1",
    "Martyrs of Tomorrow x1",
    "Màzuj Ifrit x1",
    "Angry Mob x1",
    "Fallen Angel x1",
    "Flayer x1",
    "Greater Blood Demon x1",
    "Shackled Demon x1",
    "Zeppelin of Zealots x2",
    "Cherubim x1",
    "Undesirables x1",
    "Bind Evil x2",
    "Blaze of Glory x1",
    "Flame Strike x2",
    "Lash x1",
    "Trial by Fire x2",
    "Wreathed in Righteousness x1",
    "Release the Hounds x1",
    "Active Volcano x1",
    "Autumn Bloom x1",
    "Blessed Village x1",
    "Consecrated Ground x1",
    "Desert Bloom x2",
    "Hillside Chapel x1",
    "Molten Maar x1",
    "Purgatory x1",
    "Road to Perdition x1",
    "Valley x2",
    "Vast Desert x2",
    "Wasteland x2",
  ],
  "Harbinger": [
    "Falling Star x1",
    "Aaj-kegon Ghost Crabs x1",
    "Forsaken x2",
    "Sea Witch x2",
    "Static Servant x1",
    "Willing Tribute x2",
    "Mesmer Demon x2",
    "Nommo Monitor x2",
    "Bound Spirit x2",
    "Frozen Horror x1",
    "Lacuna Entity x1",
    "Regurgitator x1",
    "Slimy Mutants x1",
    "Gnarled Wendigo x1",
    "Hearkening Kraken x1",
    "Shoggoth x2",
    "Dormant Monstrosity x1",
    "Ten-tonne Slug x2",
    "Yog-Sothoth x1",
    "Gift of the Frog x2",
    "Ice Shards x2",
    "Monstermorphosis x1",
    "Swap x1",
    "Abyssal Assault x1",
    "Into the Abyss x1",
    "Call of the Sea x1",
    "Accursed Tower x1",
    "Algae Bloom x1",
    "Croaking Swamp x2",
    "Dark Alley x1",
    "Deep Sea x1",
    "Den of Evil x1",
    "Elder Ruins x1",
    "Peculiar Port x1",
    "Spire x2",
    "Stinging Kelp x2",
    "Stream x2",
    "Twilight Bloom x1",
    "Horrible Hybrids x1",
    "Shoggoth x2",
  ],
  "Necromancer": [
    "Necromancer x1",
    "Panpipes of Pnom x1",
    "Corpse Catapult x1",
    "Bone Jumble x1",
    "Fowl Bones x2",
    "Bitter Departed x1",
    "Ignited x2",
    "Novice Necromancer x2",
    "Noxious Corpse x1",
    "Khamaseen Mummy x1",
    "Order of the Pale Worm x1",
    "Screamer x3",
    "Snallygaster x2",
    "Stygian Archers x1",
    "Hotwheel x2",
    "Dreadwing x1",
    "Master Necromancer x1",
    "Vesper Swarm x1",
    "Those Who Linger x1",
    "Draconian Bonekite x1",
    "Stitched Abomination x1",
    "Bone Spear x3",
    "Detonate x1",
    "Carrionette x1",
    "Kiss of Death x2",
    "Witching Hour x1",
    "Necronomiconcert x1",
    "Accursed Desert x1",
    "Accursed Tower x1",
    "Darkest Dungeon x1",
    "Den of Evil x1",
    "Desert Bloom x1",
    "Dread Thicket x1",
    "Forsaken Crypt x1",
    "Open Mausoleum x2",
    "Sold-out Cemetery x1",
    "Spire x2",
    "Twilight Bloom x1",
    "Vast Desert x1",
    "Wasteland x2",
  ],
};

/** Optional 10-card Collection (sideboard) per precon. */
export const PRECON_COLLECTIONS: PreconCollection = {
  "Avatar of Air": [],
  "Avatar of Earth": [],
  "Avatar of Fire": [],
  "Avatar of Water": [],
  "Flamecaller": [],
  "Sparkmage": [],
  "Waveshaper": [],
  "Geomancer": [],
  "Savior": [
    "Eltham Townsfolk x1",
    "Serava Townsfolk x1",
    "Penitent Knight x1",
  ],
  "Necromancer": [
    "Ghoul x2",
  ],
  "Persecutor": [
    "Hellhounds x3",
  ],
  "Harbinger": [
    "Horrible Hybrids x1",
    "Shoggoth x2",
  ],
};

/** Utility: parse "Name" or "Name xN" -> { name, n } */
export function parseLine(line: string): { name: string; n: number } {
  let n = 1, name = line.trim();
  const m1 = name.match(/x\s*(\d+)$/i);
  const m2 = name.match(/^(\d+)\s+(.+)$/);
  if (m1) { n = Math.max(1, parseInt(m1[1], 10)); name = name.replace(m1[0], "").trim(); }
  else if (m2) { n = Math.max(1, parseInt(m2[1], 10)); name = m2[2].trim(); }
  return { name, n };
}
